### PR TITLE
Added TypedArray and ArrayBuffer support

### PR DESCRIPTION
**Pull request by R-033**
I messed up with project a little bit and tried to add support for typed arrays
Partially works, but needs to be tested and edited

### CODE REVIEW

**Comment by PiotrDabkowski** [comment]
Wow, thank you for this! That looks really nice. Still, some work has to be done to speed it up, but since it's an extra feature and it does not break the main functionality I will merge right now. 

I will clean everything up next week after I am done with my coursework :) Now I will just modify it so numpy is an optional dependency. 

Once again thank you!

**Comment by PiotrDabkowski** [comment]
Also, don't worry about code quality checks, these tools don't understand the way Js2Py is designed and tricks like argument injections etc.

**Comment by R-033** [comment]
Thanks :)

**Comment by PiotrDabkowski** [comment]
By the way, does this implementation work for your scripts? Js2Py is quite slow, this is not our fault - Python itself is like 20 times slower than JavaScript and Js2Py is still like 20 times slower than manual translation from JavaScript so you can expect that Js2Py translated JavaScript will be like 20*20=400 times slower than if run via V8 :(

**Comment by R-033** [comment]
This implementation allows to create arrays with fixed size and with typed elements inside with different arguments (length, another array, object)
However, it can't inherit values to child typed array and can't automatically convert new values.
If this will be implemented, typed arrays will work just like in JavaScript.
```
>>> import js2py
>>> a = js2py.eval_js('new Int8Array(5)')
>>> a
[0, 0, 0, 0, 0]
>>> type(a[0])
<class 'numpy.int8'>
>>> a[0] = 5
>>> type(a[0])
<class 'int'> # should be numpy.int8
```
```
>>> js2py.eval_js('b = new Int8Array(5); c = new Int8Array(b); b[0] = 5; c[0]')
0 # should be also 5, because we used b as c argument
```

**Comment by R-033** [comment]
I will try to fix this. If I get results, I'll create a new pull request.

**Pull request merged**
