### PR TITLE
Fix for loop update after break

### PR DESCRIPTION
**Pull request by PiotrDabkowski**
Inspired by https://github.com/PiotrDabkowski/Js2Py/pull/266

@bjones1 please let me know what you think :)

### CODE REVIEW

**Comment by bjones1** [comment]
How about this slightly simpler translation? Here, using try/except means there's no need to duplicate the update clause.

``` Python
class JS_CONTINUE_LABEL_61(Exception): pass
class JS_BREAK_LABEL_61(Exception): pass
try:
    #for JS loop
    var.put('i', Js(0.0))
    while (var.get('i')<Js(10.0)):
        try:
            class JS_CONTINUE_LABEL_62(Exception): pass
            class JS_BREAK_LABEL_62(Exception): pass
            try:
                #for JS loop
                var.put('j', Js(0.0))
                while (var.get('j')<Js(10.0)):
                    try:
                        raise JS_CONTINUE_LABEL_61("Continued")

                    except JS_CONTINUE_LABEL_62:
                        pass
                    # update
                    (var.put('j',Js(var.get('j').to_number())+Js(1))-Js(1))
            except JS_BREAK_LABEL_62:
                pass

        except JS_CONTINUE_LABEL_61:
            pass
        # update
        (var.put('i',Js(var.get('i').to_number())+Js(1))-Js(1))
except JS_BREAK_LABEL_61:
    pass
```

**Comment by PiotrDabkowski** [comment]
Thanks, we still need the dup update statement to handle standard continue (without labels). When no labels are present we do not have the try/except complication and the code also executes slightly faster. 

```py
for (var i=0;i<10;i++) {
  if (i < 5) {
    continue
  }
}
```

**Comment by bjones1** [comment]
Thanks, good point. I agree -- your original version looks good to me. Thanks for doing this!

**Comment by PiotrDabkowski** [comment]
Thanks a lot for help and inspiration!

**Comment by bjones1** [comment]
My pleasure -- thanks for this great fix!

**Comment by 4144** [comment]
now python 2 ci failing

**Pull request merged**
