### PR TITLE
Compilation plans

### PR DESCRIPTION
**Pull request by Lexcon**
At times there's a need to evaluate a lot of expressions that have the same structure. For such cases it's possible to avoid ast parsing by creating and re-using a compilation plan.

See testCompilationPlan.js in the repo for example and demonstration.

### CODE REVIEW

**Comment by PiotrDabkowski** [comment]
I did not test it yet, but if it indeed gives a performance boost then it is good :) You can try using constants.py which I wrote long time ago and is no longer used in the project, but it may be better than replacing the constants with regex. The biggest problem with Js2Py is that the translation is not that slow, execution is. Manual translation of JS to Python can be even 10 times faster than the code generated by Js2Py, but usually is only about 2-3 times faster. Thank you for your help :)

**Comment by Lexcon** [comment]
I use regexp only where necessary, fall back to regular str.replace 
already where possible, regexes are expensive.

Yes, I noticed the bottleneck is in the execution, not the compilation. 
I didn't see one obvious big corner to cut. I think the object wrapping 
is the main overhead.

Maybe multiple small micro optimizations such as:

var.registers([])

when evaluating a simple expression, when the list is empty the call can 
be taken out. I'll see in a week if I can find some ideas.

What are you using this library for or is that just a  hobby project for 
you?

**Comment by PiotrDabkowski** [comment]
It would take to much time to optimise it, it's not worth it :) People that need speed will use PyV8 which is faster than Python itself. Js2Py is just for easy integration of Python & Js - it's much easier to use and install than other solutions. It's just a fun project and I don't use it for anything in particular, at first I wanted to implement a headless webbrowser in pure python (something like PhantomJs) but that would take me too much time. What are you using it for haha?

**Comment by Lexcon** [comment]
I have a web application that I host and I got the idea to offer my 
users some server side scripting abilities using js syntax.
Currently it has an in-house 'language' only that resembles old VB 
somewhat and that I wrote a compiler for long ago.

I'm impressed by your work, it looks really complete.

**Comment by PiotrDabkowski** [comment]
Good luck then, I hope Js2Py is good enough for your needs :)

**Comment by Lexcon** [comment]
How much time did you put into this? I guess it was not a matter of a 
few hours.

**Comment by PiotrDabkowski** [comment]
Probably like 200 hours in total, but I really liked working on it and leaving it half finished would be pointless. Now I am focusing all my efforts on machine learning though

**Comment by Lexcon** [comment]
The speed competition is not V8, the competition is "can a javascript 
snippet speed wise run in the python-converted arena"

My assessment after a bit of going through the code is that a two fold 
speed gain would be doable with conventional trickery. For instance a brance

if instanceof(x, a): bla()
elif instanceof(x, b): bla2()
elif instanceof(x, c...
...

could be converted to use a dict of functions:

myBranchFunctions = {a: bla, b: bla2}
myBranchFunctions[typeof(a)]()

which would save a lot of bytecode level opcodes. There's a bit of room 
for such things but not an order of magnitude, as said I think two fold 
speed gain.

It would be interesting to see what would happen using Cython, I assume 
also 2 fold with unmodified code but with cython specific hints it might 
be more.

I like the idea of using this library as a 'cool to have', but I'm still 
not decided yet. Maybe I'll play with it a bit more later coming weeks. 
I'll keep you posted. I still think it's a neat piece of work.

**Pull request merged**
